INSERT INTO [dbo].[Countries] (Uid, IsActive, CreatedAt, UpdatedAt, Name, Iso2, Iso3) VALUES 
(NEWID(),1,GETDATE(),null,'Afghanistan','AF','AFG'),
(NEWID(),1,GETDATE(),null,'Aland Islands','AX','ALA'),
(NEWID(),1,GETDATE(),null,'Albania','AL','ALB'),
(NEWID(),1,GETDATE(),null,'Algeria','DZ','DZA'),
(NEWID(),1,GETDATE(),null,'American Samoa','AS','ASM'),
(NEWID(),1,GETDATE(),null,'Andorra','AD','AND'),
(NEWID(),1,GETDATE(),null,'Angola','AO','AGO'),
(NEWID(),1,GETDATE(),null,'Anguilla','AI','AIA'),
(NEWID(),1,GETDATE(),null,'Antarctica','AQ','ATA'),
(NEWID(),1,GETDATE(),null,'Antigua and Barbuda','AG','ATG'),
(NEWID(),1,GETDATE(),null,'Argentina','AR','ARG'),
(NEWID(),1,GETDATE(),null,'Armenia','AM','ARM'),
(NEWID(),1,GETDATE(),null,'Aruba','AW','ABW'),
(NEWID(),1,GETDATE(),null,'Australia','AU','AUS'),
(NEWID(),1,GETDATE(),null,'Austria','AT','AUT'),
(NEWID(),1,GETDATE(),null,'Azerbaijan','AZ','AZE'),
(NEWID(),1,GETDATE(),null,'Bahamas','BS','BHS'),
(NEWID(),1,GETDATE(),null,'Bahrain','BH','BHR'),
(NEWID(),1,GETDATE(),null,'Bangladesh','BD','BGD'),
(NEWID(),1,GETDATE(),null,'Barbados','BB','BRB'),
(NEWID(),1,GETDATE(),null,'Belarus','BY','BLR'),
(NEWID(),1,GETDATE(),null,'Belgium','BE','BEL'),
(NEWID(),1,GETDATE(),null,'Belize','BZ','BLZ'),
(NEWID(),1,GETDATE(),null,'Benin','BJ','BEN'),
(NEWID(),1,GETDATE(),null,'Bermuda','BM','BMU'),
(NEWID(),1,GETDATE(),null,'Bhutan','BT','BTN'),
(NEWID(),1,GETDATE(),null,'Bolivia','BO','BOL'),
(NEWID(),1,GETDATE(),null,'Bonaire, Sint Eustatius and Saba','BQ','BES'),
(NEWID(),1,GETDATE(),null,'Bosnia and Herzegovina','BA','BIH'),
(NEWID(),1,GETDATE(),null,'Botswana','BW','BWA'),
(NEWID(),1,GETDATE(),null,'Bouvet Island','BV','BVT'),
(NEWID(),1,GETDATE(),null,'Brazil','BR','BRA'),
(NEWID(),1,GETDATE(),null,'British Indian Ocean Territory','IO','IOT'),
(NEWID(),1,GETDATE(),null,'Brunei','BN','BRN'),
(NEWID(),1,GETDATE(),null,'Bulgaria','BG','BGR'),
(NEWID(),1,GETDATE(),null,'Burkina Faso','BF','BFA'),
(NEWID(),1,GETDATE(),null,'Burundi','BI','BDI'),
(NEWID(),1,GETDATE(),null,'Cambodia','KH','KHM'),
(NEWID(),1,GETDATE(),null,'Cameroon','CM','CMR'),
(NEWID(),1,GETDATE(),null,'Canada','CA','CAN'),
(NEWID(),1,GETDATE(),null,'Cape Verde','CV','CPV'),
(NEWID(),1,GETDATE(),null,'Cayman Islands','KY','CYM'),
(NEWID(),1,GETDATE(),null,'Central African Republic','CF','CAF'),
(NEWID(),1,GETDATE(),null,'Chad','TD','TCD'),
(NEWID(),1,GETDATE(),null,'Chile','CL','CHL'),
(NEWID(),1,GETDATE(),null,'China','CN','CHN'),
(NEWID(),1,GETDATE(),null,'Christmas Island','CX','CXR'),
(NEWID(),1,GETDATE(),null,'Cocos (Keeling) Islands','CC','CCK'),
(NEWID(),1,GETDATE(),null,'Colombia','CO','COL'),
(NEWID(),1,GETDATE(),null,'Comoros','KM','COM'),
(NEWID(),1,GETDATE(),null,'Congo','CG','COG'),
(NEWID(),1,GETDATE(),null,'Cook Islands','CK','COK'),
(NEWID(),1,GETDATE(),null,'Costa Rica','CR','CRI'),
(NEWID(),1,GETDATE(),null,'Ivory Coast','CI','CIV'),
(NEWID(),1,GETDATE(),null,'Croatia','HR','HRV'),
(NEWID(),1,GETDATE(),null,'Cuba','CU','CUB'),
(NEWID(),1,GETDATE(),null,'Curacao','CW','CUW'),
(NEWID(),1,GETDATE(),null,'Cyprus','CY','CYP'),
(NEWID(),1,GETDATE(),null,'Czech Republic','CZ','CZE'),
(NEWID(),1,GETDATE(),null,'Democratic Republic of the Congo','CD','COD'),
(NEWID(),1,GETDATE(),null,'Denmark','DK','DNK'),
(NEWID(),1,GETDATE(),null,'Djibouti','DJ','DJI'),
(NEWID(),1,GETDATE(),null,'Dominica','DM','DMA'),
(NEWID(),1,GETDATE(),null,'Dominican Republic','DO','DOM'),
(NEWID(),1,GETDATE(),null,'Ecuador','EC','ECU'),
(NEWID(),1,GETDATE(),null,'Egypt','EG','EGY'),
(NEWID(),1,GETDATE(),null,'El Salvador','SV','SLV'),
(NEWID(),1,GETDATE(),null,'Equatorial Guinea','GQ','GNQ'),
(NEWID(),1,GETDATE(),null,'Eritrea','ER','ERI'),
(NEWID(),1,GETDATE(),null,'Estonia','EE','EST'),
(NEWID(),1,GETDATE(),null,'Ethiopia','ET','ETH'),
(NEWID(),1,GETDATE(),null,'Falkland Islands (Malvinas)','FK','FLK'),
(NEWID(),1,GETDATE(),null,'Faroe Islands','FO','FRO'),
(NEWID(),1,GETDATE(),null,'Fiji','FJ','FJI'),
(NEWID(),1,GETDATE(),null,'Finland','FI','FIN'),
(NEWID(),1,GETDATE(),null,'France','FR','FRA'),
(NEWID(),1,GETDATE(),null,'French Guiana','GF','GUF'),
(NEWID(),1,GETDATE(),null,'French Polynesia','PF','PYF'),
(NEWID(),1,GETDATE(),null,'French Southern Territories','TF','ATF'),
(NEWID(),1,GETDATE(),null,'Gabon','GA','GAB'),
(NEWID(),1,GETDATE(),null,'Gambia','GM','GMB'),
(NEWID(),1,GETDATE(),null,'Georgia','GE','GEO'),
(NEWID(),1,GETDATE(),null,'Germany','DE','DEU'),
(NEWID(),1,GETDATE(),null,'Ghana','GH','GHA'),
(NEWID(),1,GETDATE(),null,'Gibraltar','GI','GIB'),
(NEWID(),1,GETDATE(),null,'Greece','GR','GRC'),
(NEWID(),1,GETDATE(),null,'Greenland','GL','GRL'),
(NEWID(),1,GETDATE(),null,'Grenada','GD','GRD'),
(NEWID(),1,GETDATE(),null,'Guadaloupe','GP','GLP'),
(NEWID(),1,GETDATE(),null,'Guam','GU','GUM'),
(NEWID(),1,GETDATE(),null,'Guatemala','GT','GTM'),
(NEWID(),1,GETDATE(),null,'Guernsey','GG','GGY'),
(NEWID(),1,GETDATE(),null,'Guinea','GN','GIN'),
(NEWID(),1,GETDATE(),null,'Guinea-Bissau','GW','GNB'),
(NEWID(),1,GETDATE(),null,'Guyana','GY','GUY'),
(NEWID(),1,GETDATE(),null,'Haiti','HT','HTI'),
(NEWID(),1,GETDATE(),null,'Heard Island and McDonald Islands','HM','HMD'),
(NEWID(),1,GETDATE(),null,'Honduras','HN','HND'),
(NEWID(),1,GETDATE(),null,'Hong Kong','HK','HKG'),
(NEWID(),1,GETDATE(),null,'Hungary','HU','HUN'),
(NEWID(),1,GETDATE(),null,'Iceland','IS','ISL'),
(NEWID(),1,GETDATE(),null,'India','IN','IND'),
(NEWID(),1,GETDATE(),null,'Indonesia','ID','IDN'),
(NEWID(),1,GETDATE(),null,'Iran','IR','IRN'),
(NEWID(),1,GETDATE(),null,'Iraq','IQ','IRQ'),
(NEWID(),1,GETDATE(),null,'Ireland','IE','IRL'),
(NEWID(),1,GETDATE(),null,'Isle of Man','IM','IMN'),
(NEWID(),1,GETDATE(),null,'Israel','IL','ISR'),
(NEWID(),1,GETDATE(),null,'Italy','IT','ITA'),
(NEWID(),1,GETDATE(),null,'Jamaica','JM','JAM'),
(NEWID(),1,GETDATE(),null,'Japan','JP','JPN'),
(NEWID(),1,GETDATE(),null,'Jersey','JE','JEY'),
(NEWID(),1,GETDATE(),null,'Jordan','JO','JOR'),
(NEWID(),1,GETDATE(),null,'Kazakhstan','KZ','KAZ'),
(NEWID(),1,GETDATE(),null,'Kenya','KE','KEN'),
(NEWID(),1,GETDATE(),null,'Kiribati','KI','KIR'),
(NEWID(),1,GETDATE(),null,'Kosovo','XK','---'),
(NEWID(),1,GETDATE(),null,'Kuwait','KW','KWT'),
(NEWID(),1,GETDATE(),null,'Kyrgyzstan','KG','KGZ'),
(NEWID(),1,GETDATE(),null,'Laos','LA','LAO'),
(NEWID(),1,GETDATE(),null,'Latvia','LV','LVA'),
(NEWID(),1,GETDATE(),null,'Lebanon','LB','LBN'),
(NEWID(),1,GETDATE(),null,'Lesotho','LS','LSO'),
(NEWID(),1,GETDATE(),null,'Liberia','LR','LBR'),
(NEWID(),1,GETDATE(),null,'Libya','LY','LBY'),
(NEWID(),1,GETDATE(),null,'Liechtenstein','LI','LIE'),
(NEWID(),1,GETDATE(),null,'Lithuania','LT','LTU'),
(NEWID(),1,GETDATE(),null,'Luxembourg','LU','LUX'),
(NEWID(),1,GETDATE(),null,'Macao','MO','MAC'),
(NEWID(),1,GETDATE(),null,'Macedonia','MK','MKD'),
(NEWID(),1,GETDATE(),null,'Madagascar','MG','MDG'),
(NEWID(),1,GETDATE(),null,'Malawi','MW','MWI'),
(NEWID(),1,GETDATE(),null,'Malaysia','MY','MYS'),
(NEWID(),1,GETDATE(),null,'Maldives','MV','MDV'),
(NEWID(),1,GETDATE(),null,'Mali','ML','MLI'),
(NEWID(),1,GETDATE(),null,'Malta','MT','MLT'),
(NEWID(),1,GETDATE(),null,'Marshall Islands','MH','MHL'),
(NEWID(),1,GETDATE(),null,'Martinique','MQ','MTQ'),
(NEWID(),1,GETDATE(),null,'Mauritania','MR','MRT'),
(NEWID(),1,GETDATE(),null,'Mauritius','MU','MUS'),
(NEWID(),1,GETDATE(),null,'Mayotte','YT','MYT'),
(NEWID(),1,GETDATE(),null,'Mexico','MX','MEX'),
(NEWID(),1,GETDATE(),null,'Micronesia','FM','FSM'),
(NEWID(),1,GETDATE(),null,'Moldava','MD','MDA'),
(NEWID(),1,GETDATE(),null,'Monaco','MC','MCO'),
(NEWID(),1,GETDATE(),null,'Mongolia','MN','MNG'),
(NEWID(),1,GETDATE(),null,'Montenegro','ME','MNE'),
(NEWID(),1,GETDATE(),null,'Montserrat','MS','MSR'),
(NEWID(),1,GETDATE(),null,'Morocco','MA','MAR'),
(NEWID(),1,GETDATE(),null,'Mozambique','MZ','MOZ'),
(NEWID(),1,GETDATE(),null,'Myanmar (Burma)','MM','MMR'),
(NEWID(),1,GETDATE(),null,'Namibia','NA','NAM'),
(NEWID(),1,GETDATE(),null,'Nauru','NR','NRU'),
(NEWID(),1,GETDATE(),null,'Nepal','NP','NPL'),
(NEWID(),1,GETDATE(),null,'Netherlands','NL','NLD'),
(NEWID(),1,GETDATE(),null,'New Caledonia','NC','NCL'),
(NEWID(),1,GETDATE(),null,'New Zealand','NZ','NZL'),
(NEWID(),1,GETDATE(),null,'Nicaragua','NI','NIC'),
(NEWID(),1,GETDATE(),null,'Niger','NE','NER'),
(NEWID(),1,GETDATE(),null,'Nigeria','NG','NGA'),
(NEWID(),1,GETDATE(),null,'Niue','NU','NIU'),
(NEWID(),1,GETDATE(),null,'Norfolk Island','NF','NFK'),
(NEWID(),1,GETDATE(),null,'North Korea','KP','PRK'),
(NEWID(),1,GETDATE(),null,'Northern Mariana Islands','MP','MNP'),
(NEWID(),1,GETDATE(),null,'Norway','NO','NOR'),
(NEWID(),1,GETDATE(),null,'Oman','OM','OMN'),
(NEWID(),1,GETDATE(),null,'Pakistan','PK','PAK'),
(NEWID(),1,GETDATE(),null,'Palau','PW','PLW'),
(NEWID(),1,GETDATE(),null,'Palestine','PS','PSE'),
(NEWID(),1,GETDATE(),null,'Panama','PA','PAN'),
(NEWID(),1,GETDATE(),null,'Papua New Guinea','PG','PNG'),
(NEWID(),1,GETDATE(),null,'Paraguay','PY','PRY'),
(NEWID(),1,GETDATE(),null,'Peru','PE','PER'),
(NEWID(),1,GETDATE(),null,'Phillipines','PH','PHL'),
(NEWID(),1,GETDATE(),null,'Pitcairn','PN','PCN'),
(NEWID(),1,GETDATE(),null,'Poland','PL','POL'),
(NEWID(),1,GETDATE(),null,'Portugal','PT','PRT'),
(NEWID(),1,GETDATE(),null,'Puerto Rico','PR','PRI'),
(NEWID(),1,GETDATE(),null,'Qatar','QA','QAT'),
(NEWID(),1,GETDATE(),null,'Reunion','RE','REU'),
(NEWID(),1,GETDATE(),null,'Romania','RO','ROU'),
(NEWID(),1,GETDATE(),null,'Russia','RU','RUS'),
(NEWID(),1,GETDATE(),null,'Rwanda','RW','RWA'),
(NEWID(),1,GETDATE(),null,'Saint Barthelemy','BL','BLM'),
(NEWID(),1,GETDATE(),null,'Saint Helena','SH','SHN'),
(NEWID(),1,GETDATE(),null,'Saint Kitts and Nevis','KN','KNA'),
(NEWID(),1,GETDATE(),null,'Saint Lucia','LC','LCA'),
(NEWID(),1,GETDATE(),null,'Saint Martin','MF','MAF'),
(NEWID(),1,GETDATE(),null,'Saint Pierre and Miquelon','PM','SPM'),
(NEWID(),1,GETDATE(),null,'Saint Vincent and the Grenadines','VC','VCT'),
(NEWID(),1,GETDATE(),null,'Samoa','WS','WSM'),
(NEWID(),1,GETDATE(),null,'San Marino','SM','SMR'),
(NEWID(),1,GETDATE(),null,'Sao Tome and Principe','ST','STP'),
(NEWID(),1,GETDATE(),null,'Saudi Arabia','SA','SAU'),
(NEWID(),1,GETDATE(),null,'Senegal','SN','SEN'),
(NEWID(),1,GETDATE(),null,'Serbia','RS','SRB'),
(NEWID(),1,GETDATE(),null,'Seychelles','SC','SYC'),
(NEWID(),1,GETDATE(),null,'Sierra Leone','SL','SLE'),
(NEWID(),1,GETDATE(),null,'Singapore','SG','SGP'),
(NEWID(),1,GETDATE(),null,'Sint Maarten','SX','SXM'),
(NEWID(),1,GETDATE(),null,'Slovakia','SK','SVK'),
(NEWID(),1,GETDATE(),null,'Slovenia','SI','SVN'),
(NEWID(),1,GETDATE(),null,'Solomon Islands','SB','SLB'),
(NEWID(),1,GETDATE(),null,'Somalia','SO','SOM'),
(NEWID(),1,GETDATE(),null,'South Africa','ZA','ZAF'),
(NEWID(),1,GETDATE(),null,'South Georgia and the South Sandwich Islands','GS','SGS'),
(NEWID(),1,GETDATE(),null,'South Korea','KR','KOR'),
(NEWID(),1,GETDATE(),null,'South Sudan','SS','SSD'),
(NEWID(),1,GETDATE(),null,'Spain','ES','ESP'),
(NEWID(),1,GETDATE(),null,'Sri Lanka','LK','LKA'),
(NEWID(),1,GETDATE(),null,'Sudan','SD','SDN'),
(NEWID(),1,GETDATE(),null,'Suriname','SR','SUR'),
(NEWID(),1,GETDATE(),null,'Svalbard and Jan Mayen','SJ','SJM'),
(NEWID(),1,GETDATE(),null,'Swaziland','SZ','SWZ'),
(NEWID(),1,GETDATE(),null,'Sweden','SE','SWE'),
(NEWID(),1,GETDATE(),null,'Switzerland','CH','CHE'),
(NEWID(),1,GETDATE(),null,'Syria','SY','SYR'),
(NEWID(),1,GETDATE(),null,'Taiwan','TW','TWN'),
(NEWID(),1,GETDATE(),null,'Tajikistan','TJ','TJK'),
(NEWID(),1,GETDATE(),null,'Tanzania','TZ','TZA'),
(NEWID(),1,GETDATE(),null,'Thailand','TH','THA'),
(NEWID(),1,GETDATE(),null,'Timor-Leste (East Timor)','TL','TLS'),
(NEWID(),1,GETDATE(),null,'Togo','TG','TGO'),
(NEWID(),1,GETDATE(),null,'Tokelau','TK','TKL'),
(NEWID(),1,GETDATE(),null,'Tonga','TO','TON'),
(NEWID(),1,GETDATE(),null,'Trinidad and Tobago','TT','TTO'),
(NEWID(),1,GETDATE(),null,'Tunisia','TN','TUN'),
(NEWID(),1,GETDATE(),null,'Turkey','TR','TUR'),
(NEWID(),1,GETDATE(),null,'Turkmenistan','TM','TKM'),
(NEWID(),1,GETDATE(),null,'Turks and Caicos Islands','TC','TCA'),
(NEWID(),1,GETDATE(),null,'Tuvalu','TV','TUV'),
(NEWID(),1,GETDATE(),null,'Uganda','UG','UGA'),
(NEWID(),1,GETDATE(),null,'Ukraine','UA','UKR'),
(NEWID(),1,GETDATE(),null,'United Arab Emirates','AE','ARE'),
(NEWID(),1,GETDATE(),null,'United Kingdom','GB','GBR'),
(NEWID(),1,GETDATE(),null,'United States','US','USA'),
(NEWID(),1,GETDATE(),null,'United States Minor Outlying Islands','UM','UMI'),
(NEWID(),1,GETDATE(),null,'Uruguay','UY','URY'),
(NEWID(),1,GETDATE(),null,'Uzbekistan','UZ','UZB'),
(NEWID(),1,GETDATE(),null,'Vanuatu','VU','VUT'),
(NEWID(),1,GETDATE(),null,'Vatican City','VA','VAT'),
(NEWID(),1,GETDATE(),null,'Venezuela','VE','VEN'),
(NEWID(),1,GETDATE(),null,'Vietnam','VN','VNM'),
(NEWID(),1,GETDATE(),null,'Virgin Islands, British','VG','VGB'),
(NEWID(),1,GETDATE(),null,'Virgin Islands, US','VI','VIR'),
(NEWID(),1,GETDATE(),null,'Wallis and Futuna','WF','WLF'),
(NEWID(),1,GETDATE(),null,'Western Sahara','EH','ESH'),
(NEWID(),1,GETDATE(),null,'Yemen','YE','YEM'),
(NEWID(),1,GETDATE(),null,'Zambia','ZM','ZMB'),
(NEWID(),1,GETDATE(),null,'Zimbabwe','ZW','ZWE');