INSERT INTO dbo.Cities (Uid, CreatedAt, IsActive, Name, CountryId) VALUES 
(NEWID(), GETDATE(),1, 'Dubai', 234),
(NEWID(), GETDATE(),1, 'Abu Dhabi', 234),
(NEWID(), GETDATE(),1, 'Sharjah', 234),
(NEWID(), GETDATE(),1, 'Al Ain', 234),
(NEWID(), GETDATE(),1, 'Ajman', 234),
(NEWID(), GETDATE(),1, 'Ras Al Khaimah', 234),
(NEWID(), GETDATE(),1, 'Fujairah', 234),
(NEWID(), GETDATE(),1, 'Umm al-Quwain', 234),
(NEWID(), GETDATE(),1, 'Dibba Al-Fujairah', 234),
(NEWID(), GETDATE(),1, 'Khor Fakkan', 234),
(NEWID(), GETDATE(),1, 'Kalba', 234),
(NEWID(), GETDATE(),1, 'Jebel Ali', 234),
(NEWID(), GETDATE(),1, 'Madinat Zayed', 234),
(NEWID(), GETDATE(),1, 'Ruwais', 234),
(NEWID(), GETDATE(),1, 'Liwa Oasis', 234),
(NEWID(), GETDATE(),1, 'Dhaid', 234),
(NEWID(), GETDATE(),1, 'Ghayathi', 234),
(NEWID(), GETDATE(),1, 'Ar-Rams', 234),
(NEWID(), GETDATE(),1, 'Dibba Al-Hisn', 234),
(NEWID(), GETDATE(),1, 'Hatta', 234),
(NEWID(), GETDATE(),1, 'Al Madam', 234),
(NEWID(), GETDATE(),1, 'Al Jazirah Al Hamra', 234);